version: '3.7'
services:
    postgres:
        image: postgres:latest
        restart: always
        hostname: postgres
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
          - dm
        ports:
          - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        volumes:
          - ./database/postgres-data:/var/lib/postgresql/data
          - ./database/data_manager_setup.sql:/docker-entrypoint-initdb.d/data_manager_setup.sql
    database-admin:
      image: dpage/pgadmin4:latest
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - "5050:80"
      volumes:
        - ./database/servers.json:/pgadmin4/servers.json
        - ./database/admin:/var/lib/pgadmin
      links:
        - "postgres:pgsql-server"
      depends_on:
        - postgres
      networks:
        - dm
    api:
        build: data-manager-api/.
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_PORT=${POSTGRES_PORT}
          - POSTGRES_HOST=${POSTGRES_HOST}
          - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
        ports:
          - '8080:8080'
        links:
          - postgres
        networks:
          - dm
    web:
        build: frontend/.
        ports:
          - '3000:3000'
        links:
          - api
        networks:
          - dm
networks:
  dm: