apiVersion: networking.k8s.io/v1
kind: LoadBalancer
metadata:
  name: data-manager-ingress-api

spec:
  ingressClassName: alb
  rules:
  - host: {{ .Values.ingressapi.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: data-manager-api
            port:
              number: 8080