apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-manager-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 852056369035.dkr.ecr.us-west-2.amazonaws.com/data-manager:latest
          ports:
            - containerPort: 3000