# Default values for data-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

aws-load-balancer-controller:
  clusterName: data-manager-eks
  serviceAccount:
    create: false
    name: aws-load-balancer-controller

api:
  serviceName: api
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    postgres_user: admin
    postgres_password: ""
    postgres_port: "5432"
    postgres_host: postgres
    postgres_db_name: postgres
  image:
    repository: ""
    pullPolicy: IfNotPresent
    tag: "latest"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

frontend:
  serviceName: frontend
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
  env:
    graphql_url: "http://localhost:8080/graphql"
  image:
    repository: ""
    pullPolicy: IfNotPresent
    tag: "latest"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
postgresql:
  image:
    debug: true

  auth:
    postgresPassword: ""
    username: "admin"
    password: ""
    database: "postgres"

  primary:
    volumePermissions:
      enabled: true
    persistence:
      enabled: false # TODO set to true, use EBS
      existingClaim: postgres-pvc
    initdb:
      user: "admin"
      password: ""
      scripts:
        db-init.sql: |
          CREATE TABLE feeds (
              id serial PRIMARY KEY,
              vendor TEXT,
              feed_name TEXT,
              feed_method TEXT);
          INSERT INTO feeds (vendor, feed_name, feed_method )
          VALUES ('GoodRx', 'Claims', 'SFTP'),
          ('The Advisory Board', 'Physicians', 'S3');
          CREATE TABLE feed_status (
              id serial PRIMARY KEY,
              feed_id INTEGER REFERENCES feeds (id),
              process_date TEXT,
              record_count INTEGER,
              error_count INTEGER,
              feed_status TEXT);
          INSERT INTO feed_status (feed_id, process_date, record_count, error_count, feed_status)
          VALUES (1, '09/27/2018', 1958623, 0, 'success'),
          (1, '09/23/2016', 2389635, 61, 'errors'),
          (2, '10/15/2017', 0, 500, 'failed'),
          (2, '03/24/2018', 13076, 0, 'success');

# https://github.com/rowanruseler/helm-charts/blob/master/charts/pgadmin4/values.yaml
pgadmin4:
  persistentVolume:
    enabled: false
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  ingress:
    enabled: true
    ingressClassName: "alb"
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      ingressclass.kubernetes.io/is-default-class: "true"
    hosts:
      - paths:
          - path: /
            pathType: Prefix
  env:
    email: ""
    password: ""
  serverDefinitions:
    enabled: true
    servers:
     dataManagerServer:
       Name: "Data Manager Postgres Server"
       Group: "Servers"
       Port: 5432
       Username: "admin"
       Host: "data-manager-postgresql"
       SSLMode: "disable"
       MaintenanceDB: "postgres"

ingressfrontend:
  host: ""

ingressapi:
  host: ""

ingresspgadmin:
  host: ""