apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-manager-{{ .Values.api.serviceName }}
  labels:
    {{- include "data-manager.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "data-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "data-manager.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: "POSTGRES_USER"
              value:  {{ .Values.api.env.postgres_user }}
            - name: "POSTGRES_PASSWORD"
              value:  {{ .Values.api.env.postgres_password }}
            - name: "POSTGRES_PORT"
              value: "{{ .Values.api.env.postgres_port }}"
            - name: "POSTGRES_HOST"
              value: {{ .Values.api.env.postgres_host }}
            - name: "POSTGRES_DB_NAME"
              value: {{ .Values.api.env.postgres_db_name }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
