apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/name: external-dns
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
        app.kubernetes.io/instance: external-dns
    spec:
      serviceAccountName: aws-load-balancer-controller
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.11.0
          args:
          - --source=service
          - --source=ingress
          - --provider=aws
          - --aws-zone-type=public
          - --registry=txt
          - --txt-owner-id={{ .Values.hostedZoneId }}
          env:
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.awsRegion }}
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes and AWS token files
