apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-manager-ingress-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingressbackend.host }}
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: data-manager-api
            port:
              number: 8080
      - path: /pgadmin(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: data-manager-pgadmin4
            port:
              number: 5050