apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-manager-ingress-api
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    ingressclass.kubernetes.io/is-default-class: "true"
    external-dns.alpha.kubernetes.io/hostname: api.{{ .Values.domainName }}
spec:
  ingressClassName: "alb"
  rules:
    - host: api.{{ .Values.domainName }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: data-manager-api
              port:
                number: 8080