apiVersion: v1
kind: Service
metadata:
  name: data-manager-api
  labels:
    {{- include "data-manager.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.{{ .Values.domainName }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "data-manager.selectorLabels" . | nindent 4 }}

